name: parking_user
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  cloud_firestore: ^4.3.1
  convex_bottom_bar: ^3.1.0+1
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  floating_bottom_bar: ^0.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.0.0
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.2
  intl: ^0.17.0
  pin_entry_text_field: ^0.1.4

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
