name: parking_user
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.8

dependencies:
  bloc: ^8.1.0
  calendar_view: ^1.0.1
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.3.1
  convex_bottom_bar: ^3.1.0+1
  curved_navigation_bar: ^1.0.3
  firebase_auth: ^4.1.0
  firebase_core: ^2.1.1
  firebase_storage: ^11.0.10
  floating_bottom_bar: ^0.0.1
  flutter:
    sdk: flutter
  flutter_animation_progress_bar: ^2.3.1
  flutter_bloc: ^8.1.1
  flutter_datetime_picker: ^1.5.1
  flutter_localizations:
    sdk: flutter
  flutter_map: ^3.0.0
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  font_awesome_flutter: ^10.3.0
  get: ^4.6.5
  getwidget: ^3.0.1
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.2
  image_picker: ^0.8.6
  intl: ^0.17.0
  pin_entry_text_field: ^0.1.4
  shared_preferences: ^2.0.15
  syncfusion_flutter_barcodes: ^20.4.43
  syncfusion_flutter_calendar: ^20.4.43
  table_calendar: ^3.0.8
  uuid: ^3.0.7
  xml: ^6.1.0

dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/images/
